//@prepros-append assets/plugins/jquery1.11.2.min.js
//@prepros-append assets/plugins/bootstrap.min.js
//@prepros-append assets/plugins/jquery.easing.1.3.min.js
//@prepros-append assets/plugins/jquery.countTo.js
//@prepros-append assets/plugins/jquery.formchimp.min.js
//@prepros-append assets/plugins/jquery.jCounter-0.1.4.js
//@prepros-append assets/plugins/jquery.magnific-popup.min.js
//@prepros-append assets/plugins/jquery.vide.min.js
//@prepros-append assets/plugins/owl.carousel.min.js
//@prepros-append assets/plugins/spectragram.min.js
//@prepros-append assets/plugins/twitterFetcher_min.js
//@prepros-append assets/plugins/wow.min.js
//@prepros-append assets/plugins/picker.js
//@prepros-append assets/plugins/picker.date.js